# Generated by Django 6.0.2 on 2026-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_activate_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('kg', 'Kilogram')], default='pcs', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
