# Generated by Django 6.0.2 on 2026-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0),
        ),
    ]
