# Generated by Django 6.0.2 on 2026-02-16 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=998000000000, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 bilan boshlanib, 9 ta raqamdan iborat bo‘lishi kerak', regex='^\\+998\\d{9}$')]),
            preserve_default=False,
        ),
    ]
